// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2021_1_kekEnd/internal/movies (interfaces: UseCase)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	models "github.com/go-park-mail-ru/2021_1_kekEnd/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockUseCase is a mock of UseCase interface.
type MockUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockUseCaseMockRecorder
}

// MockUseCaseMockRecorder is the mock recorder for MockUseCase.
type MockUseCaseMockRecorder struct {
	mock *MockUseCase
}

// NewMockUseCase creates a new mock instance.
func NewMockUseCase(ctrl *gomock.Controller) *MockUseCase {
	mock := &MockUseCase{ctrl: ctrl}
	mock.recorder = &MockUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUseCase) EXPECT() *MockUseCaseMockRecorder {
	return m.recorder
}

// CreateMovie mocks base method.
func (m *MockUseCase) CreateMovie(arg0 *models.Movie) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMovie", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMovie indicates an expected call of CreateMovie.
func (mr *MockUseCaseMockRecorder) CreateMovie(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMovie", reflect.TypeOf((*MockUseCase)(nil).CreateMovie), arg0)
}

// GetAllGenres mocks base method.
func (m *MockUseCase) GetAllGenres() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGenres")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGenres indicates an expected call of GetAllGenres.
func (mr *MockUseCaseMockRecorder) GetAllGenres() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGenres", reflect.TypeOf((*MockUseCase)(nil).GetAllGenres))
}

// GetBestMovies mocks base method.
func (m *MockUseCase) GetBestMovies(arg0 int, arg1 string) (int, []*models.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBestMovies", arg0, arg1)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]*models.Movie)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBestMovies indicates an expected call of GetBestMovies.
func (mr *MockUseCaseMockRecorder) GetBestMovies(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBestMovies", reflect.TypeOf((*MockUseCase)(nil).GetBestMovies), arg0, arg1)
}

// GetMovie mocks base method.
func (m *MockUseCase) GetMovie(arg0, arg1 string) (*models.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMovie", arg0, arg1)
	ret0, _ := ret[0].(*models.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMovie indicates an expected call of GetMovie.
func (mr *MockUseCaseMockRecorder) GetMovie(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMovie", reflect.TypeOf((*MockUseCase)(nil).GetMovie), arg0, arg1)
}

// GetMoviesByGenres mocks base method.
func (m *MockUseCase) GetMoviesByGenres(arg0 []string, arg1 int, arg2 string) (int, []*models.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMoviesByGenres", arg0, arg1, arg2)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]*models.Movie)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMoviesByGenres indicates an expected call of GetMoviesByGenres.
func (mr *MockUseCaseMockRecorder) GetMoviesByGenres(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMoviesByGenres", reflect.TypeOf((*MockUseCase)(nil).GetMoviesByGenres), arg0, arg1, arg2)
}

// GetSimilar mocks base method.
func (m *MockUseCase) GetSimilar(arg0 string) ([]models.Movie, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSimilar", arg0)
	ret0, _ := ret[0].([]models.Movie)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSimilar indicates an expected call of GetSimilar.
func (mr *MockUseCaseMockRecorder) GetSimilar(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSimilar", reflect.TypeOf((*MockUseCase)(nil).GetSimilar), arg0)
}

// MarkUnwatched mocks base method.
func (m *MockUseCase) MarkUnwatched(arg0 models.User, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUnwatched", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUnwatched indicates an expected call of MarkUnwatched.
func (mr *MockUseCaseMockRecorder) MarkUnwatched(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUnwatched", reflect.TypeOf((*MockUseCase)(nil).MarkUnwatched), arg0, arg1)
}

// MarkWatched mocks base method.
func (m *MockUseCase) MarkWatched(arg0 models.User, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkWatched", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkWatched indicates an expected call of MarkWatched.
func (mr *MockUseCaseMockRecorder) MarkWatched(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkWatched", reflect.TypeOf((*MockUseCase)(nil).MarkWatched), arg0, arg1)
}
